#pragma once

#define IDR_VANILLA_ITEMSTATCOST 201
#define IDR_VANILLA_PROPERTIES 202
#define IDR_VANILLA_MAGICSUFFIX 203
#define IDR_VANILLA_MAGICPREFIX 204
#define IDR_VANILLA_AUTOMAGIC 205
#define IDR_VANILLA_QUALITYITEMS 206
#define IDR_VANILLA_UNIQUEITEMS 207
#define IDR_VANILLA_SETITEMS 208
#define IDR_VANILLA_ARMOR 209
#define IDR_VANILLA_ITEMTYPES 210
#define IDR_VANILLA_WEAPONS 211
#define IDR_VANILLA_MISC 212
#define IDR_VANILLA_GEMS 213
#define IDR_VANILLA_RUNES 214
#define IDR_VANILLA_CUBEMAIN 215
