cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED HOOK_MANIFEST OR HOOK_MANIFEST STREQUAL "")
	message(FATAL_ERROR "HOOK_MANIFEST must name the manifest to validate")
endif()

if(NOT EXISTS "${HOOK_MANIFEST}")
	message(FATAL_ERROR "Hook manifest does not exist: ${HOOK_MANIFEST}")
endif()

file(READ "${HOOK_MANIFEST}" manifest_json)
string(JSON manifest_type TYPE "${manifest_json}")
if(NOT manifest_type STREQUAL "OBJECT")
	message(FATAL_ERROR "Hook manifest root must be a JSON object")
endif()

string(JSON schema_version GET "${manifest_json}" schemaVersion)
if(NOT schema_version EQUAL 1)
	message(FATAL_ERROR "Unsupported hook manifest schemaVersion '${schema_version}'")
endif()

string(JSON target_build GET "${manifest_json}" targetBuild)
if(NOT target_build STREQUAL "3.2.92777")
	message(FATAL_ERROR "Hook manifest targetBuild must be '3.2.92777', got '${target_build}'")
endif()

string(JSON sites_type TYPE "${manifest_json}" sites)
if(NOT sites_type STREQUAL "ARRAY")
	message(FATAL_ERROR "Hook manifest 'sites' member must be an array")
endif()

string(JSON site_count LENGTH "${manifest_json}" sites)
if(site_count LESS 1)
	message(FATAL_ERROR "Hook manifest must contain at least one site")
endif()

set(allowed_owners plugin-items plugin-levels plugin-misc plugin-quests plugin-skills)
set(allowed_kinds byte-patch call-site inline-hook nop)
set(seen_ids)
math(EXPR last_site "${site_count} - 1")

foreach(index RANGE 0 ${last_site})
	string(JSON site_type TYPE "${manifest_json}" sites ${index})
	if(NOT site_type STREQUAL "OBJECT")
		message(FATAL_ERROR "Hook manifest site ${index} must be an object")
	endif()

	foreach(field IN ITEMS id owner feature kind rva length expectedBytes source)
		string(JSON field_type TYPE "${manifest_json}" sites ${index} ${field})
		if(field STREQUAL "length")
			if(NOT field_type STREQUAL "NUMBER")
				message(FATAL_ERROR "Site ${index} field '${field}' must be a number")
			endif()
		else()
			if(NOT field_type STREQUAL "STRING")
				message(FATAL_ERROR "Site ${index} field '${field}' must be a string")
			endif()
		endif()
	endforeach()

	string(JSON site_id GET "${manifest_json}" sites ${index} id)
	string(JSON owner GET "${manifest_json}" sites ${index} owner)
	string(JSON feature GET "${manifest_json}" sites ${index} feature)
	string(JSON kind GET "${manifest_json}" sites ${index} kind)
	string(JSON rva_text GET "${manifest_json}" sites ${index} rva)
	string(JSON write_length GET "${manifest_json}" sites ${index} length)
	string(JSON expected_bytes GET "${manifest_json}" sites ${index} expectedBytes)
	string(JSON source GET "${manifest_json}" sites ${index} source)

	if(site_id STREQUAL "" OR feature STREQUAL "" OR source STREQUAL "")
		message(FATAL_ERROR "Site ${index} has an empty id, feature, or source")
	endif()

	if(site_id IN_LIST seen_ids)
		message(FATAL_ERROR "Duplicate hook manifest id '${site_id}'")
	endif()
	list(APPEND seen_ids "${site_id}")

	if(NOT owner IN_LIST allowed_owners)
		message(FATAL_ERROR "Site '${site_id}' has unknown owner '${owner}'")
	endif()
	if(NOT kind IN_LIST allowed_kinds)
		message(FATAL_ERROR "Site '${site_id}' has unknown write kind '${kind}'")
	endif()
	if(NOT source MATCHES "^src/${owner}/")
		message(FATAL_ERROR "Site '${site_id}' source '${source}' is outside its owner '${owner}'")
	endif()

	if(NOT rva_text MATCHES "^0x[0-9A-Fa-f]+$")
		message(FATAL_ERROR "Site '${site_id}' has invalid RVA '${rva_text}'")
	endif()
	math(EXPR rva "${rva_text}")
	if(write_length LESS 1)
		message(FATAL_ERROR "Site '${site_id}' has invalid length '${write_length}'")
	endif()
	math(EXPR write_end "${rva} + ${write_length}")

	if(NOT expected_bytes MATCHES "^[0-9A-Fa-f][0-9A-Fa-f]( [0-9A-Fa-f][0-9A-Fa-f])*$")
		message(FATAL_ERROR "Site '${site_id}' has malformed expectedBytes '${expected_bytes}'")
	endif()
	string(REGEX MATCHALL "[0-9A-Fa-f][0-9A-Fa-f]" expected_byte_list "${expected_bytes}")
	list(LENGTH expected_byte_list expected_byte_count)
	if(NOT expected_byte_count EQUAL write_length)
		message(FATAL_ERROR
			"Site '${site_id}' length ${write_length} does not match ${expected_byte_count} expected bytes")
	endif()

	if(index GREATER 0)
		math(EXPR previous_last "${index} - 1")
		foreach(previous RANGE 0 ${previous_last})
			if(rva LESS site_${previous}_end AND site_${previous}_rva LESS write_end)
				message(FATAL_ERROR
					"Memory-write overlap: '${site_id}' (${owner}, ${rva_text}, length ${write_length}) overlaps "
					"'${site_${previous}_id}' (${site_${previous}_owner}, ${site_${previous}_rva_text}, length ${site_${previous}_length})")
			endif()
		endforeach()
	endif()

	set(site_${index}_id "${site_id}")
	set(site_${index}_owner "${owner}")
	set(site_${index}_rva "${rva}")
	set(site_${index}_rva_text "${rva_text}")
	set(site_${index}_length "${write_length}")
	set(site_${index}_end "${write_end}")
endforeach()

message(STATUS "Hook manifest VALID: ${site_count} uniquely owned sites for D2R ${target_build}")
